# Generated by Django 4.0.5 on 2022-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
